import type { CriticInput } from "./buildCriticPrompt.ts";
import type { LlmCriticOutput } from "./criticSchema.ts";

const MOCK_CAUTION = "This report was generated by the mock critic provider. It is useful for development and layout testing, not interpretation quality.";

const PATTERN_NAMES = [
  "Rule Pressure Gate",
  "Final State Attractor",
  "Compression Drift",
  "Dead Cluster Candidate",
  "Rewrite Bottleneck"
];

export function buildMockCriticOutput(input: CriticInput): LlmCriticOutput {
  const topRule = Object.entries(input.stats.ruleUsageCounts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0];
  const commonState = input.stats.mostCommonFinalStates[0];
  const patternName = choosePatternName(input);
  const topRuleId = topRule?.[0] ?? input.puzzle.rules[0]?.id ?? "R?";
  const topRuleUsage = topRule?.[1] ?? 0;

  return {
    summary: `Mock critic provider summary for ${input.puzzle.id}: observed ${input.stats.runCount} solver traces with best score ${input.stats.bestScore}. This is deterministic development output, not an LLM interpretation.`,
    observedPatterns: [
      {
        title: patternName,
        evidence: topRule
          ? `Rule ${topRuleId} was the most used rule in this batch (${topRuleUsage} applications).`
          : "No rule usage dominance was available in the stats.",
        confidence: topRuleUsage > input.stats.runCount ? "medium" : "low"
      },
      {
        title: "Final State Attractor",
        evidence: commonState
          ? `The most common final state was ${commonState.state} (${commonState.count} runs).`
          : `The run set produced ${input.stats.distinctFinalStates} distinct final states.`,
        confidence: commonState && commonState.count / Math.max(1, input.stats.runCount) >= 0.35 ? "medium" : "low"
      }
    ],
    possibleInvariants: [
      {
        name: "Rewrite Bottleneck Candidate",
        description: `The observed pressure around ${topRuleId} may indicate a local rewrite bottleneck.`,
        whyItMightMatter: "If the pattern survives mutation tests, it can guide future puzzle evolution.",
        confidence: "low"
      }
    ],
    failureEcology: [
      {
        failureMode: input.stats.averageFinalLength > input.puzzle.initial.length ? "Expansion drift" : "Compression stall",
        evidence: `Average final length was ${input.stats.averageFinalLength.toFixed(2)} from initial length ${input.puzzle.initial.length}.`,
        possibleCause: "The current rule set may bias solvers toward a local basin rather than stable compression."
      }
    ],
    nextExperiments: [
      {
        title: `Mutate ${topRuleId}`,
        change: `Alter or temporarily remove ${topRuleId}, then rerun the same solver mix with the same seed count.`,
        expectedObservation: "If the pattern is meaningful, best score, convergence, or distinct final states should shift noticeably."
      },
      {
        title: "Increase random seed count",
        change: "Run more random solver seeds while keeping puzzle rules fixed.",
        expectedObservation: "A robust pattern candidate should remain visible under a larger batch."
      }
    ],
    mathFlavor: ["string rewriting systems", "local search", "attractor candidates", "compression"],
    humanMetaphor: "A mock observatory plate: enough shadow to test the telescope, not enough to name the star.",
    madowakuNameCandidates: [patternName, "Mock Fold Gate", "Development Attractor"],
    cautions: [
      MOCK_CAUTION,
      "Do not treat this output as model interpretation.",
      "Use it to develop report layout, provider plumbing, and mutation-plan structure."
    ]
  };
}

function choosePatternName(input: CriticInput): string {
  const index = Math.abs(input.stats.bestScore + input.stats.distinctFinalStates + input.stats.seed) % PATTERN_NAMES.length;
  return PATTERN_NAMES[index];
}
